### ISSUE TITLE
Issue with !pod.yaml and queries

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#110]
I think any YAML queries (e.g. files that use `?foo.bar` to query for specific data within a YAML file) are perhaps handled incorrectly, e.g.

![image](https://user-images.githubusercontent.com/646525/125866258-87ed266f-a0b3-49a3-a2ac-fb6e2b363088.png)

**Comment by jeremydw** [comment]
Similar issue seen in this screenshot: 
![image](https://user-images.githubusercontent.com/646525/125868835-bbdb6896-8c47-498b-a4de-86638c568329.png)

**Comment by Zoramite** [comment]
I think that this might be a 'filter' problem where the filtered list of files is only the `/content/` files.

**Comment by Zoramite** [comment]
The files were being filtered by the connector. This is being updated to return a full set of files for the project and then the UI will be responsible for filtering to just the files it needs from the full set.

See: https://github.com/blinkk/editor.dev/commit/69fd6e26727461b3b6c7a3a52c2108ff025c4f6e
