### ISSUE TITLE
Fix inconsistent button styles

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#115]
The button styles within the field editor need to match the rest of the UI. They're still using the styles from the old editor.

![image](https://user-images.githubusercontent.com/646525/126248294-73db543f-0242-4e8d-94a5-8d7b3f8874be.png)

**Comment by jeremydw** [comment]
Buttons also need specific foreground colors; when the system is in dark mode but the user has chosen light mode certain buttons can be illegible.

![image](https://user-images.githubusercontent.com/646525/126265121-ae281cef-24a8-4423-a88e-49c0ff840da3.png)

**Comment by jeremydw** [comment]
Variant button also impacted by the system dark theme 
![image](https://user-images.githubusercontent.com/646525/127094991-8028a7d9-b747-40d0-8e93-6f9ca716d439.png)

**Comment by Zoramite** [comment]
The latest UI changes for monochromatic should fix the issues with the buttons.
