### ISSUE TITLE
[object Object] visible when !pod.yaml is used with media

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#119]
[Example here](https://beta.editor.dev/gh/blinkk/google-hsw/main/content/pages/how-search-works.yaml)

![image](https://user-images.githubusercontent.com/646525/126675684-6ff56d6c-fe7d-4eed-9963-2c5f8f00d1d9.png)

**Comment by Zoramite** [comment]
Is is part of the discussion and will be fixed when that is fixed: https://github.com/blinkk/editor.dev-ui/discussions/86

**Comment by Zoramite** [comment]
I'm going to lower the priority on this for now since we have the messages now when the data format is not the expected value. We still need a long term fix as discussed in #86, but it doesn't need to be as high a priority.

**Comment by jeremydw** [comment]
Thank you! Confirmed I can round-trip save without destroying the data either.

One more thing to knock out here - I still see an `[object Object]` in the label. This may look like an error to the user so can we add some code to avoid this?

It can be `{Item 1}` or `Unknown` or something. Anything to avoid the `[object Object]` which looks like a system bug.

![image](https://user-images.githubusercontent.com/646525/129071932-daba0d91-c578-4d4c-86b6-231b08e4a8ab.png)

**Comment by Zoramite** [comment]
I've updated the label finding process to exclude non-string values from being possible label values. That should fix most of the cases when a label is being shown as an Object.
