### ISSUE TITLE
Superfluous [object Object] field visible at top

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#124]
Not sure what this is, but it shouldn't be there.

Maybe it's an auto-guessed title? If so, it should have a label indicating it's the title (and the value should be updated).

[Example](https://beta.editor.dev/gh/blinkk/google-hsw/main/content/pages/index.yaml)

![image](https://user-images.githubusercontent.com/646525/126706189-e0710b04-4a9b-4049-8cdc-1e6f9de37e6d.png)

**Comment by jeremydw** [comment]
It's also on the source tab (FYI)

![image](https://user-images.githubusercontent.com/646525/126706283-25b7ca00-a0b4-49b8-8d26-b3b7e5cf7393.png)

**Comment by Zoramite** [comment]
Fixed already in one of the other PRs.
