### ISSUE TITLE
Infinite loop when unable to load project

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#128]
Steps to reproduce:
1. Run `npx @blinkk/editor.dev` in a folder that just has a `views/partials` directory
2. Ensure the directory has no commits in it (but is a valid git repo)

Observe attached screenshot

![image](https://user-images.githubusercontent.com/646525/126722441-3c92fdec-f010-47f3-960f-95771b4830f0.png)

**Comment by Zoramite** [comment]
When there is no project information, many parts of the editor try to load the project config. But when there is an error getting the project information the editor keeps trying to load the project which causes an infinite loop of requests to load the project.
