### ISSUE TITLE
Panels need refresh buttons

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#133]
@micjamking Could we get your opinion on where to place it?

**Comment by jeremydw** [comment]
We should also have a refresh button on the left panel as well. This is useful during development when the developer may want to iterate constantly on the fields/schema setup. Currently the only way to reload the fields is to refresh the whole page.

**Comment by micjamking** [comment]
Updated mocks with refresh icons; for the left editor menu panel, I've added a new footer section which includes the theme settings and the refresh icon, for the middle editor panel, I've included the refresh icon in the "Developer Tools" section.

<img width="812" alt="Screen Shot 2021-07-23 at 5 32 21 PM" src="https://user-images.githubusercontent.com/651702/126856219-d378dd20-680c-4b85-8eaf-5eecc55996a2.png">

**Comment by jeremydw** [comment]
NOTE: Reload button for the fields panel might be useful for non-devs too. It can serve as a way to "discard changes" and reload whatever was from GitHub.

**Comment by micjamking** [comment]
I've updated the mocks with a refresh icon in the editor panel header, near the localization and panel expansion icons:

<img width="600" alt="Screen Shot 2021-08-12 at 3 52 29 PM" src="https://user-images.githubusercontent.com/651702/129293963-17c96961-f3d6-492d-899f-cd7dc7fbc3af.png">

Note: this mock current replaces the environment links in the previous iterations (see screenshot below), however I noticed this feature is no longer included in the current version of the app. If we're still looking to support this idea in the future, then I will revise the mocks further. Please let me know.

<img width="601" alt="Screen Shot 2021-08-12 at 3 53 14 PM" src="https://user-images.githubusercontent.com/651702/129294149-2235fc97-9c64-41fb-94f5-686711c8c778.png">

**Comment by Zoramite** [comment]
The links are supported in the current version, I just have not added them into the api response yet to point to the correct places:

![image](https://user-images.githubusercontent.com/107076/129306427-71cbf667-0ae9-4328-a939-35e6330b7267.png)

**Comment by jeremydw** [comment]
Right-side refresh buttons look great to me. Let's add them as soon as we can since they'll be really useful during the development phase of building out Editor sites.

Regarding the link buttons - we can have a deeper discussion around those. I'm wondering if we may want to put those links inside an action menu (and therefore use text links instead). For me personally it is hard to remember what each icon means.

**Comment by Zoramite** [comment]
I'm really curious how much you will end up using this as I usually find it a lot faster to switch to the browser and use `Cmd + R` to refresh.

How much you will use it if you have to use the mouse to navigate to refresh the settings vs refreshing the whole page. Especially when you are doing it against a local code base since it doesn't take long for the refresh to happen.

**Comment by Zoramite** [comment]
Or a better way of saying that: we should have some keyboard shortcut that makes this process easier than having to click the icon for power users who don't want to refresh the entire app.
