### ISSUE TITLE
UI tweaks to variant fields

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#134]
- I think we should hide the "Variant:" label that appears to the left of the variations -- the term "variant" is probably a bit unfriendly to the standard content editor, and I think any clarification could be made by the developer in the field's help text.

- There needs to be a way to "clear" the selection

Steps to reproduce the clear issue:

1. Visit https://beta.editor.dev/example/?path=%2Fexample%2Fstructure.yaml
2. Click "hero"
3. Put some text into the field
4. Clear the text
5. Notice that I can't choose "Hero with image" until I refresh the whole page

I think a "clear" button next to the variant labels would fix the issue

**Comment by Zoramite** [comment]
Removed the variant label and added an icon for clearing the current value for the variant.

![image](https://user-images.githubusercontent.com/107076/127065677-205cd601-2e87-45d9-9e52-258b5e2ae128.png)
