### ISSUE TITLE
Need UI for "actions" menu for partials

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#137]
I think it's time we replace the "delete" icon with a "three dots" actions menu for partials.

Proposed actions in the menu:

- Insert row above
- Insert row below
- Duplicate row
- Delete row

Similar to Google Sheets:

![image](https://user-images.githubusercontent.com/646525/126822110-600668d5-fec1-4f11-b2dd-27f4ffe4cbc6.png)

![image](https://user-images.githubusercontent.com/646525/126821950-26f4591a-50ef-4e2f-94eb-d6e260ed29a3.png)

**Comment by micjamking** [comment]
Updated Figma mocks with context menu example:

<img width="530" alt="Screen Shot 2021-07-23 at 5 29 57 PM" src="https://user-images.githubusercontent.com/651702/126856151-763e3397-2646-415f-b607-5d8bc85c5b4d.png">

**Comment by micjamking** [comment]
Dark Mode:

<img width="580" alt="Screen Shot 2021-08-12 at 3 39 08 PM" src="https://user-images.githubusercontent.com/651702/129292788-4f4c6629-104f-4e0a-8c80-cae3b7cbffd2.png">
<img width="582" alt="Screen Shot 2021-08-12 at 3 39 31 PM" src="https://user-images.githubusercontent.com/651702/129292793-0c1cb203-1f69-45e8-ba31-fa45e451cd58.png">
