### ISSUE TITLE
Add backend type icon to top right

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#138]
I can have lots of editors open, e.g. one tab with a GitHub editor and one tab with a local editor. We should add an icon representing the backend type to the top right next to the Git project info:

![image](https://user-images.githubusercontent.com/646525/126823265-3d0436f3-7e52-4469-be3e-ba61fa129669.png)

- For GitHub, we can add the GitHub Octocat icon to the left of the branch name and link to the branch
- For local, we can add the local laptop icon (no link)

**Comment by micjamking** [comment]
Updated Figma mocks with icons:

**Github backend**
<img width="744" alt="Screen Shot 2021-07-23 at 5 28 17 PM" src="https://user-images.githubusercontent.com/651702/126856112-4b11f77a-a348-4cec-82c2-f50c2606e949.png">

**Local backend**
<img width="779" alt="Screen Shot 2021-07-23 at 5 28 00 PM" src="https://user-images.githubusercontent.com/651702/126856111-52e07a6e-24c8-47f2-93cc-01cdc96db751.png">
