### ISSUE TITLE
Update style / theme of left file menu panel; missing separators between panels

### ISSUE THREAD

**Issue by micjamking** [blinkk/editor.dev-ui#143]
The current editor is missing distinct separations between the panels; this is most notable when no files have been selected:

<img width="1440" alt="Screen Shot 2021-07-23 at 5 36 44 PM" src="https://user-images.githubusercontent.com/651702/126856331-0e098248-b03f-4e6f-914c-1ecd4860ff3b.png">

...and when there is no preview available.

<img width="1440" alt="Screen Shot 2021-07-23 at 5 41 20 PM" src="https://user-images.githubusercontent.com/651702/126856363-ca8081ef-1a83-4d11-9012-d680529a4a4d.png">

I think the UI would benefit visually from clearer distinctions between the panels. The mocks have always included a 1px border separating the editor and preview panel, using the same grey color as the editor developer tools footer pane, but is easy to miss unless zooming in.

<img width="999" alt="Screen Shot 2021-07-23 at 5 38 04 PM" src="https://user-images.githubusercontent.com/651702/126856409-8f64cf9f-9f2e-42bc-84dd-4cbe61e9d6b0.png">

I've also updated the styles for the left file menu panel, which I think makes the panel distinction clearer

**Menu Expanded** 
<img width="1440" alt="Mocks_ Edit Page _ Browser Menu Expanded" src="https://user-images.githubusercontent.com/651702/126856445-fbf80fd9-3360-45d3-8696-cc1fc4a4f4df.png">

**Menu Docked**
<img width="1440" alt="Mocks_ Edit Page _ Browser Menu Expanded - Docked" src="https://user-images.githubusercontent.com/651702/126856273-56aa8123-5d3c-4f76-a398-f88d176a944d.png">

I think these changes would also apply to the color theming, however I think we should avoid changing some of the font-color / action items since the client branding/theming could potentially clash with editor colors with predefined meaning (e.g. https://www.gradient.com/ uses red for its primary color, the entire UI may give the appearance of an error 😝 )

Let me know what you folks think @Zoramite & @jeremydw .

**Comment by Zoramite** [comment]
Keeping the menu with the normal panel styling for now and not doing the high contrast look. We can discuss it more later if we change our mind.
