### ISSUE TITLE
Need UI for "actions" menu for files

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#151]
Also time to think about the actions menu for files in the file tree.

A few ideas for menu items:

- Duplicate
- Delete
- Rename ( #248 )
- (For GitHub) Copy to another workspace ( #249 )
- (For GitHub) Open in GitHub (with `new_window` icon) ( #250 )
- (Enabled based on whether the file has preview) Open preview (with `new_window` icon) ( #251 )

**Comment by micjamking** [comment]
Updated Figma mocks with file actions menu example:

<img width="349" alt="Screen Shot 2021-08-12 at 2 46 15 PM" src="https://user-images.githubusercontent.com/651702/129287913-bad9c976-9c94-43ce-b79e-09aa0456bbbe.png">
<img width="351" alt="Screen Shot 2021-08-12 at 2 45 02 PM" src="https://user-images.githubusercontent.com/651702/129287922-3b711819-1c64-4cd2-a5c5-62770803df61.png">

I've also added an example workspace actions menu example:

<img width="300" alt="Screen Shot 2021-08-12 at 2 50 44 PM" src="https://user-images.githubusercontent.com/651702/129287954-1fde5553-e5c2-4b75-9ab4-bb23ea2adaba.png">
<img width="301" alt="Screen Shot 2021-08-12 at 2 51 26 PM" src="https://user-images.githubusercontent.com/651702/129287957-c63f3d9f-fa86-4dd8-aca1-d53eb5b845df.png">

**Comment by micjamking** [comment]
Dark mode:
<img width="352" alt="Screen Shot 2021-08-12 at 3 24 51 PM" src="https://user-images.githubusercontent.com/651702/129291920-621ec2fe-9388-4593-9191-393d0067b22e.png">
<img width="351" alt="Screen Shot 2021-08-12 at 3 25 31 PM" src="https://user-images.githubusercontent.com/651702/129291926-dede7d26-a2d7-4ffc-8220-cee33cbdd8d1.png">
<img width="300" alt="Screen Shot 2021-08-12 at 3 26 05 PM" src="https://user-images.githubusercontent.com/651702/129291927-b1762ec3-b292-4974-a45a-8367da776ba5.png">
<img width="301" alt="Screen Shot 2021-08-12 at 3 26 34 PM" src="https://user-images.githubusercontent.com/651702/129291929-e3d32647-482b-494b-8d82-b7b29fffc13b.png">

**Comment by jeremydw** [comment]
Looks good but I have nitpicky feedback on the font size. The font size looks too small to me... maybe we just keep it the same size as the other UI labels?

Figma example where the same font size is used for the popup:

![image](https://user-images.githubusercontent.com/646525/129396367-42b7f5d4-7566-43fa-965e-525049d44572.png)

![image](https://user-images.githubusercontent.com/646525/129396414-8e620d5c-96e1-48e6-b398-977b28c8e219.png)

**Comment by Zoramite** [comment]
I'm going to open separate issues for some of the new ideas for menu items since they will each require a different set of new features to work.
