### ISSUE TITLE
Tooltip on server icon interferes with clickability

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#152]
The tooltip makes it hard to click the server icon -- only the top half of the icon is actually clickable.

![image](https://user-images.githubusercontent.com/646525/127265090-4e3a5867-43c5-45c8-8377-03bdce119ef0.png)

**Comment by Zoramite** [comment]
This should be fixed with the latest UI updates. I turned off the pointer events for the tooltip so it should not interfere with the click target.
