### ISSUE TITLE
Improve error message when using invalid fields

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#154]
Currently, when I make a schema change that's invalid, I get an error message like:

```
Unable to add field for unknown field type: undefined.
```

It would be better if it included the whole field configuration, so I could know which field exactly is the incorrect one. Right now, if I add 10 fields and one is incorrect, it is very hard to figure out which field is broken.

Would also probably be good to have a UI indicator in the field list indicating the broken field, but an improved error message in the Devtools would be a good start.

**Comment by adelaidemt** [comment]
This task requires: 
1) change the error message to make it actionable for the developer
2) message to show that the field is broken
