### ISSUE TITLE
Increase tertiary color contrast

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#177]
Colors indicated in screenshot need to be darker. OK to use the same `var(--color-on-list-item-background)` if there is no other superior option.

![image](https://user-images.githubusercontent.com/646525/128117756-1dea528a-bdfd-4f33-b6eb-31c3c6fec21f.png)

**Comment by micjamking** [comment]
@jeremydw The font-styling of the menu headers & icons are actually a bit off from the mocks; do you feel the mocks need to be adjusted further, or will it be sufficient to match the mocks (see attached)?

Here's the current font-style for the menu headers (from Figma):
```css
font-family: SF Pro Text; /* ie. --system-font */
font-style: normal;
font-weight: bold;
font-size: 12px;
line-height: 14px;
text-transform: uppercase;
color: #AAAAAA;
```

Additionally, the icons for sections/folders (underneath the "Site" menu heading) should match the text color of the section / folder (ie. black in this case).

<img width="351" alt="Screen Shot 2021-08-12 at 4 02 27 PM" src="https://user-images.githubusercontent.com/651702/129294624-8102a299-3129-4fba-9cd9-5c7e8a714b1f.png">

**Comment by Zoramite** [comment]
I've targeted the 'lighter' style icons to just the non-special leaf nodes, which I think matches what the mocks are showing:

![image](https://user-images.githubusercontent.com/107076/129384460-e82f77f5-f1ee-4c37-814e-0d4e93bd209b.png)

**Comment by jeremydw** [comment]
Hi All - I do think the grey needs to be updated in the mocks as well since it is too light. Using the built-in Devtools accessibility tester you can see that it doesn't fully pass the contrast check. 

![image](https://user-images.githubusercontent.com/646525/129384778-7ab4a097-7824-4819-9d21-c84e7867757c.png)

Example of passing the contrast check:

![image](https://user-images.githubusercontent.com/646525/129384837-12c70593-1be5-4dfb-b135-53280e0c568c.png)

**Comment by Zoramite** [comment]
To get it to pass the accessibility contrast, we would have to bump it up to something like #585858

![image](https://user-images.githubusercontent.com/107076/129390356-4a028ca8-a4ee-4183-8a30-a3b26e1d48e5.png)

And at that point it would probably be better to just use the same color as the label.

**Comment by micjamking** [comment]
I'd prefer updating the non-leaf nodes to the lightest accessible grey (ie. `#767676`) along with updating the parent sections/folders nodes to the same font-weight styling from the mocks (ie. `font-weight: bold`, see screenshots); there's not enough differentiation between the leaf/non-leaf nodes as-is, and the styling should be consistent with the titles in the editor panel.

<img width="351" alt="Screen Shot 2021-08-12 at 4 02 27 PM" src="https://user-images.githubusercontent.com/651702/129413598-204cc105-8836-4ceb-9e44-1c1fd10dd16d.png">
<img width="598" alt="Screen Shot 2021-08-13 at 10 16 01 AM" src="https://user-images.githubusercontent.com/651702/129413972-acfd36ac-1e1e-4ed1-8713-25e1947337a9.png">

**Comment by jeremydw** [comment]
Lightest accessible grey is looking good to me. :) Thank you for working through these!

**Comment by Zoramite** [comment]
Alrighty, I've adjusted it to have a darker grey color for the leaf icons.

![image](https://user-images.githubusercontent.com/107076/129415073-297fa7e0-0cee-458d-9dec-097b1a3c9e66.png)
