### ISSUE TITLE
Handling editor version upgrades 

### ISSUE THREAD

**Issue by adelaidemt** [blinkk/editor.dev-ui#199]
Every branch of every project can have its own version of the editor. This makes it hard to manage bugs that are fixed in newer versions but there isn't a way to tell if the current version of the editor is the latest. 

Some ideas:

- Should be able to tell what version of the editor is currently in use and what is that latest available.
- When there is a non-breaking release, allow for user to update the version of the editor. ex: 1.0.0 → 1.0.x
- When there is a breaking release, just let the user know that they are out of date. Ex: 1.0.0 → 2.x.x
- Needs to be somewhere in the UI where it is not obtrusive if they don't want to change versions. Aka, not forceful, but lets the user know there is an update. Maybe just a regular notice in the notifications.

More complex issues:

- The editor can be used in different place (ex: amagaki, grow, oak, etc). So what one does to upgrade the editor isn't the same as what another does to upgrade.
    - The grow plugin uses the editor, but is maintained outside of the editor.
    - The upgrade can only happen with the grow extension updates its dependency and recompiles.
- Update check should have two pieces: The version of the `live-editor` and the version of the third-party library it is used in. The UI can show the version of the `live-editor` but should only prompt for update if the third-party library has an upgrade.

**Comment by jeremydw** [comment]
This is resolved within the overall design of Editor.dev

**Comment by adelaidemt** [comment]
This is why I needed you a lookover of the Notion board :)
