### ISSUE TITLE
Grid overlay/toggle in preview pane

### ISSUE THREAD

**Issue by adelaidemt** [blinkk/editor.dev-ui#204]

**Comment by jeremydw** [comment]
We're going to group features related to the preview in https://github.com/blinkk/editor.dev-ui/issues/207

Note we may make these features part of the https://github.com/blinkk/amagaki-plugin-preview project as many of the features will require integration between how the site is actually built. We can experiment with the preview plugin - see how it works - and make generic later if needed.
