### ISSUE TITLE
Preview options modal

### ISSUE THREAD

**Issue by adelaidemt** [blinkk/editor.dev-ui#207]
To make the editor more flexible with the way that previews are shown, we can have a 'settings' for the preview pane when the project settings are configured for it.

For instance, the preview could support a grid overlay, module overlay, etc. So in the editor they could click on the preview settings and show a modal with form fields (ex: checkboxes, radio, etc) that would then be sent to the preview url (ex: `?editor=true&grid=true&modules=true&animal=monkey`)

**Comment by Zoramite** [comment]
Duplicate of #170
