### ISSUE TITLE
Missing partials auto guessing for project type fields.

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#213]
[This page](https://beta.editor.dev/gh/blinkk/google-gmail/test/content/pages/index.yaml) is a mix of autoguess-ed and configured partials. The third partial in the list is both:

1. Not using the schema from the partial [link](https://github.com/blinkk/google-gmail/blob/workspace/test/views/partials/tabset.njk)
2. Autoguessing incorrectly

**Comment by Zoramite** [comment]
Some fields are project type specific (like the `partials` field) and are not yet integrated into the autoguessing for the editor.

**Comment by Zoramite** [comment]
Looking into it more, the project type specific auto guessing is being used, but doesn't support `partials` yet.
