### ISSUE TITLE
Suggestion for autoguess fields and extended types

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#95]
For any extended types (e.g. `!pod.yaml`), we currently show a field that allows the user to (presumably) change the type. In practice, it might be useful to edit the value of the field, but not the type itself. Similarly, for autoguess-ed standard fields, one can't convert a text type to a boolean type, etc.

So, to make the autoguess + extended type scenario more useful, I suggest we simply hide the "type" from the fields (see attached screenshot).

In the future, we could improve the autoguess fields for certain types (e.g. `!pod.doc`) to add pickers, but in the interim, it would be a nice improvement to just hide the type from the list of fields, since editing the type is not really a use case (outside of editing the source directly).

Thoughts?

![image](https://user-images.githubusercontent.com/646525/125321311-6a19bf00-e2f1-11eb-88d1-d8f19a6844a9.png)

**Comment by Zoramite** [comment]
So, this is actually a broken auto guess.

The json format for the yaml types comes across as `{_type: "pod.yaml", _data: "..."}`. So the auto guess should be able to use that information to do one field that is a `yaml` type.

I think that the piece that is missing at the moment is having a project type specific auto guess class. Right now it knows how to handle the normal guessing, but it breaks down on fields that are specific to a project type (ex: amagaki/grow).
