### ISSUE TITLE
Update default preview pane behavior

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#97]
Currently, the preview pane and associated UI only appears when:

- The project has a preview server configured
- The current file appears in the preview server's routes.json
- Perhaps 1 more condition?

We should make a few changes to better support the preview workflow and make the UI a little less conditional:

1. Always show the preview UI button. If a project doesn't have a preview server configured, we can display a message within the frame explaining how to set it up.

2. For projects with a preview configured, before the routes.json has loaded, show a loading indicator within the preview frame.

3. For files that don't have a preview configured (i.e. no entry in routes.json), show a message within the frame saying that the current file does not have a preview associated with it.

These changes should accomplish a few things:

a. Make the UI more consistent and there be less guess-work around the previews
b. Help folks set up previews
c. Make things feel snappier because we can show loading progress, etc. and it doesn't happen "under the hood" with the user wondering if a preview is going to show up eventually for the current project/file

**Comment by jeremydw** [comment]
One more quality of life suggestion for this. If the user has the preview pane open, Editor should load the fields and the preview simultaneously.

Right now it seems like the fields load first (since the whole page is taken over with "Loading..."), then the preview loads. But I think we can speed it up by separating the loading states to be contained within the panels, and loading the preview pane immediately based on the data currently present from `routes.json` / simultaneously with loading the fields. Is that right?

![image](https://user-images.githubusercontent.com/646525/125335871-e7e5c680-e301-11eb-8486-aa5da4ab497d.png)

**Comment by Zoramite** [comment]
The preview iframe can only be loaded at the same time when the preview server's routes info has already been loaded (ex: when switching pages after the editor loads, but not the first page load since it doesn't have the route info yet).

I am working on the change that will keep the preview pane visible instead of having it jump into existence when it gets route information. We can show either loading information when waiting for preview server information or a message that links to documentation on how to setup and run a preview server in the docs, or a message that there is no known preview for the file, etc.

**Comment by Zoramite** [comment]
I think I *can* speed up the loading of the preview server configuration by starting it earlier when it hasn't been loaded yet instead of waiting for the full file response to come back before making the request.

**Comment by jeremydw** [comment]
Latest changes are looking great; and it feels snappier.

Noticed two issues:

1. We lose the "toggle preview" icon on files that don't have previews associated with them. The "toggle preview" icon should always be there regardless of the state of the preview.
2. More of a feature request regarding the loading state -- we currently overtake the entire right side pane when a file is loading, but it would feel less jarring and feel faster if the entire pane remained as the user navigates files, and if the loading state was contained to *within* the left-side field panel (rather than overtaking the entire right side pane).

Happy to elaborate more on (2) in chat or our meeting. :)
